version: '2'
services: 
  phabricator: 
    image: phabricator:1.0.0-SNAPSHOT
    ports:
        - "80:80"
    environment:
        APACHE_ROOT_DIR: "/var/www/html"
        BASEDIR_APACHE: "/etc/httpd/"
        DOMAIN: "127.0.0.1"
        MYSQL_HOST: "127.0.0.1"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "admin"
     
