version: '2'
services: 
  phabricator: 
    image: phabricator:1.0.0-SNAPSHOT
    ports:
        - "8080:8080"
    environment:
        APACHE_ROOT_DIR: "/var/www/html"
        BASEDIR_APACHE: "/etc/httpd/"
        DOMAIN: "172.18.0.1"
        MYSQL_HOST: "172.18.0.1"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "admin"
        MYSQL_PORT: 3306
     
